### PR TITLE
Create Experience & Category models, seeding file, and unit testing for models

### PR DESCRIPTION
**Pull request by aleksdao**
Hi guys, this branch contains the following:

- Experience model (and unit testing)
- Category model (and unit testing)
- updated ./seed.js file that populates database with Experiences & Categories ("npm run seed" to seed db)
- to run testing on the models, download repo to local machine, npm install, then run `gulp testServerJS`
Please review and let me know of any comments!

### CODE REVIEW

**Comment by johnhillphoto** [comment]
Looks good to me.  Merge away!

**Comment by metzda** [comment]
I would recommend removing Reviews as a separate model, I think we need to have reviews nested under products

**Comment by metzda** [comment]
Also, enum should be removed from experiences model file and instead added as seed data.  We don't want to limit the experiences that are able to be created.

**Comment by aleksdao** [comment]
@metzda 

Regarding the Review model, it needs to be linked to both a User and an Experience. Because it needs to be connected to 2 other schemas, I figure it would make sense as a standalone Schema/model. You can also easily query for the list of reviews belonging to a User or Experience very easily -- `Experience.find({ user: some_user._id }) and Experience.find({ experience: some_experience._id })`. What would you suggest instead? Within an experience, nest a Review object that also contains a user ID? Are there benefits to that approach? I'm still trying to wrap my head around the various tradeoffs in terms of independent schemas, nesting/embedding, referencing by Id, so bear with me :) 

Regarding enum, I've only implemented that for the Category schema. My idea there was to have 10-15 high-level categories for a trip (Great for families, Sporting events, Culinary adventure, etc), which would then be applied to an experience. We could also add an "Other" enum value. I think it makes sense to define these categories ahead of time. To confirm, this does not limit the experiences that can be added... the experience is just a String type. What do you think?

**Pull request merged**
